version: '3.4'

services:
  rezhelpbackend:
    image: rezhelpbackend
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 3000:3000
