/**
 * Single Stone
 * This is the OAS file for SingeStone.  
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: apiteam@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { Name } from './name';

export class CallList {
    'phone'?: string;
    'name'?: Name;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "phone",
            "baseName": "phone",
            "type": "string"
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "Name"
        }    ];

    static getAttributeTypeMap() {
        return CallList.attributeTypeMap;
    }
}

