/**
 * Single Stone
 * This is the OAS file for SingeStone.  
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: apiteam@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class Name {
    'first'?: string;
    'middle'?: string;
    'last'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "first",
            "baseName": "first",
            "type": "string"
        },
        {
            "name": "middle",
            "baseName": "middle",
            "type": "string"
        },
        {
            "name": "last",
            "baseName": "last",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return Name.attributeTypeMap;
    }
}

