swagger: '2.0'
info:
  description: |
    This is the OAS file for SingeStone. 
  version: 1.0.0
  title: Single Stone
  termsOfService: http://swagger.io/terms/
  contact:
    email: apiteam@swagger.io
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
paths:
  /contacts:
    post:
      tags:
      - Contact
      summary: Adds a new contact to the store
      operationId: addContact
      consumes:
      - application/json
      - application/xml
      produces:
      - application/json
      - application/xml
      parameters:
      - in: body
        name: body
        description: Person object that needs to be added to the database
        required: true
        schema:
          $ref: '#/definitions/Person'
      responses:
        201: 
          description: No response
        400:
          description: Invalid input
        404:
          description: Not found
        500:
          description: Server Error
    get:
      tags:
      - Contact
      summary: Lists all contacts in the database
      description: Lists all contacts
      operationId: listContacts
      produces:
      - application/json
      - application/xml
      responses:
        200:
          description: successful operation
          schema:
            type: array
            items:
              $ref: '#/definitions/Person'
        400:
          description: Invalid status value
        404:
          description: Not found
        500:
          description: Server Error  
  /contacts/{id}:
    get:
      tags:
      - ContactById
      summary: Find person by ID
      description: Returns a single person
      operationId: getPersonById
      produces:
      - application/json
      - application/xml
      parameters:
      - name: id
        in: path
        description: ID of person to return
        required: true
        type: integer
        format: int64
      responses:
        200:
          description: successful operation
          schema:
            $ref: '#/definitions/Person'
        400:
          description: Invalid ID supplied
        404:
          description: Person not found
        500:
          description: Server Error  
    put:
      tags:
      - ContactById
      summary: Updates a person by ID
      operationId: updatePersonWithForm
      consumes:
      - application/json
      produces:
      - application/json
      - application/xml
      parameters:
      - name: id
        in: path
        description: ID of person to return
        required: true
        type: integer
        format: int64
      - in: body
        name: Person Object
        schema: 
          $ref: '#/definitions/Person'
      responses:
        201: 
          description: No response
        400:
          description: Invalid input
        500:
          description: Server Error  
    delete:
      tags:
      - ContactById
      summary: Deletes a contact
      operationId: deleteContact
      produces:
      - application/json
      - application/xml
      parameters:
      - name: id
        in: path
        description: ID of person to return
        required: true
        type: integer
        format: int64
      responses:
        201: 
          description: No response
        400:
          description: Invalid input
        404: 
          description: Not Found
  /contacts/call-list:
    get:
      tags:
      - Contact List
      summary: returns Call List
      operationId: callList
      produces:
      - application/json
      responses:
        200:
          description: successful operation
          schema:
            type: array
            items: 
              $ref: '#/definitions/CallList'
        500:
          description: Server Error        
definitions:
  Name: 
    type: object
    properties:
      first:
        type: string
      middle:
        type: string
      last: 
        type: string
        
  Address: 
    type: object
    properties:
      street:
        type: string
      city:
        type: string
      state: 
        type: string    
      zip:
        type: string
  Phone: 
    type: object
    properties:
      number:
        type: string
      type:
        type: string
  CallList: 
    type: object
    properties:
      phone: 
        type: string
      name:
          $ref: '#/definitions/Name'
  Person:
    type: object
    properties:
      id:
        type: integer
        format: int64
      name:
          $ref: '#/definitions/Name'
      address:
          $ref: '#/definitions/Address'    
      phone:
        type: array
        xml:
          name: tag
          wrapped: true
        items:
          $ref: '#/definitions/Phone'
      email:
        type: string
    xml:
      name: Person
externalDocs:
  description: Find out more about Swagger
  url: http://swagger.io
# Added by API Auto Mocking Plugin
host: localhost:3000
basePath: /
schemes:
 - https
 - http